### ISSUE TITLE
Tying PB isn't shown as PB on your profile

### ISSUE THREAD

**Issue by topppits** [euphwes/cubers.io#1]
You can see it on my profile on 2x2: https://www.cubers.io/u/topppits/

My average PB is 4.54 and last week I got another 4.54.

**Comment by euphwes** [comment]
Is this how the WCA handles tied PBs? I've perused a couple of profiles but haven't found an example of where a user has a tied PB.

**Comment by CMOSSystem** [comment]
Yes the WCA highlights all tied results, take Feliks Zemdegs' two 5.66 (WR/OcR) 3x3 singles as example

**Comment by topppits** [comment]
Definitely.

3x 22 single FMC: https://www.worldcubeassociation.org/persons/2008CLEM01?event=333fm


Just like tying a record (WR/CR/NR) also gives you the record, whether you had it before or not doesn't matter. 
2x 8.72 PB/WR: https://www.worldcubeassociation.org/persons/2007NAKA03?event=333

**Comment by euphwes** [comment]
Fixed in code and deployed. Running the script to update past PBs for everybody now, which will take a couple minutes, and from this point forward tied PBs will be indicated as PBs.
