### ISSUE TITLE
Add option for new competition notifications

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#12]
Implement optional direct user notification of new competitions being posted via Reddit PM, based on user preferences. The notifications should be placed in a background tasks queue, so that posting a new competition does not block while waiting for Reddit PMs to be sent. Depends on #11.

**Comment by gmct** [comment]
Mass PM blasts aren't allowed on reddit. We can explore expanding Pushbullet functionality as an alternative.

**Comment by euphwes** [comment]
Even as an opt-in thing? Hmm that's too bad. Public Pushbullet channel is a good idea, I'll brainstorm others.

**Comment by euphwes** [comment]
We established that this is actually ok, so long as the notifications are on an opt-in basis.
