### ISSUE TITLE
Kotlin back-end rewrite

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#127]

**Comment by marceloFA** [comment]
So the Flask backend will be replaced?

**Comment by euphwes** [comment]
I'm considering it... This project started as a small Python project with a Flask backend, but it's become large enough now that it's starting to feel a little cluttered and clumsy. I don't really have a firm timeline on this, but I do think a more performant language would be nice, plus something that's statically-typed would help make the back-end a bit easier to read and write.

Plus I tend to like picking up new languages and frameworks whenever I can find an excuse to use them, and this feels like a good candidate.

**Comment by euphwes** [comment]
@marceloFA ^

**Comment by marceloFA** [comment]
Oh, thanks for the explanation. I've read at [Kotlin documentation](https://kotlinlang.org/docs/reference/server-overview.html) that they have a few listed frameworks for web backends. Do you have the intention of considering any of the frameworks listed as the one for the reimplementation of cubers.io?

**Comment by euphwes** [comment]
I have no idea... The more I think about this, the more daunting it is. Maybe I'll abandon this and then just do some other side project to learn Kotlin.

**Comment by euphwes** [comment]
Nah, not going to do this.
