### ISSUE TITLE
Omit WCA-only users from attempted Reddit PMs, and disable Reddit options

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#128]
Currently, WCA-only users are being show Reddit Preferences in the settings page, which makes no sense since they don't have their Reddit account associated. Disable those prefs for those users, and when sending weekly PMs, only do so for users with Reddit account info.

**Comment by marceloFA** [comment]
Would you provide more details on this issue? I'm interested in start contributing in this project.

**Comment by euphwes** [comment]
Hi! Sure thing -- there are 2 ways to log into cubers.io, via your Reddit account or your WCA account. If you're logged in as a WCA user, you can also log in via Reddit in the profile page, to associate your Reddit account with your cubers.io profile. Both of these types of users will have the `reddit_id` attribute populated in the database for the cubers.io profile, and so we'll be able to send them a PM.

When I added the ability to login via WCA, I didn't go back and update the code that sends Reddit competition notifications. Right now, it just grabs the appropriate list of users, and then tries to send them a PM based on their `username` attribute in the database. For WCA users, this is their WCA ID, which obviously won't work as a Reddit username for the purpose of the PM. Does that make sense? Hopefully I'm articulating it well...

I'd also like to disable or hide the "Reddit Preferences" section of the settings page, for users who have only logged with via WCA, because we don't have their Reddit information.

To be honest, I've actually already started working on this issue and almost have the fix complete. But I'd love to have more contributors on the project! Is there another issue in the backlog you're interested in tackling?

**Comment by euphwes** [comment]
@marceloFA I've already wrapped this one up, but please dig into the other issues! Or feel free to dig into the code base and see if there's any general cleanup or refactoring that could be done. Also, I'm certainly open to other features or ideas that aren't in the backlog; if you have an idea that isn't already there, definitely open an issue and give it implementing it a shot.

**Comment by marceloFA** [comment]
Thanks for the explanation on this issue, anyways <3. About other possible contributions, I'll surely grab one and work on it. Thanks for the warm welcome on the project!
