### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by topppits** [euphwes/cubers.io#13]
- Darkmode

- sort the events in a more consistent order sth like this: 2x2-7x7, 2BLD-5BLD, MBLD, 3x3OH, 3x3WF, 3x3FMC, Skewb, Pyraminx, Megaminx, Squan, Clock, bonus events
or just the WCA order, or the order you already implemented when you click on records -> wca events

- make a visual distinction that shows which events are weekly events and which are bonus events

**Comment by euphwes** [comment]
Improved the sort order: it's now:

- weekly WCA events first (with similar events grouped)
- weekly non-WCA events (just LSE and 2GEN at the moment)
- bonus events (with similar events grouped)

Also added a visual indicator to bonus events.

Closing this, as the remaining portion (dark mode) has a separate issue open for it (#41). Thanks!
