### ISSUE TITLE
Settings page cleanup

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#134]
The user settings/preferences page was already getting a little cluttered and unwieldy, but now that I've added the ability to hide events, it's just huge. Let's break up the single settings page into several smaller ones, for each of the main sections now (timer prefs, Reddit settings, hidden events, custom cube colors, etc).

**Comment by marceloFA** [comment]
What about collapsable settings sections in some accordion-like UI? here's [an example](https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example). Sounds good?

**Comment by euphwes** [comment]
Oh that's a good idea, @marceloFA ! Thanks. I'll toy with that a bit. I'd also like to improve how some of the options are presented to the user... for example, the event list for the hide/show preferences, is unwieldy because it's just a big long list of events, one per line, with a big toggle button. Maybe I'll put those into a grid of some sort, and for each event just have a single button with the event name + icon on it, and clicking it toggles some visual enabled/disabled state.
