### ISSUE TITLE
Add podium/Medal Collection

### ISSUE THREAD

**Issue by topppits** [euphwes/cubers.io#14]
Add podium (visually) to the leaderboard and show the Medal Collection on the personal records page as soon as the user has at least one podium.

**Comment by euphwes** [comment]
I generally like it, though my concern with this is that the same handful of top users are likely to make the podiums week after week, given the fact that the participant pool is largely the same each week. This is different than real-life WCA competitions, which happen more infrequently, and each competition will generally have a different set of participants.

I think maybe a dozen of the top users would accumulate lots of podiums over time, while the remainder of the users wouldn't have any.

I guess this isn't too different than IRL competitions... I certainly don't have any chance at real podiums either! I'll chew on it.
