### ISSUE TITLE
Show overall leaderboard 

### ISSUE THREAD

**Issue by topppits** [euphwes/cubers.io#15]
Add a live overall ranking to the leaderboard.

**Comment by euphwes** [comment]
Do you mean similar to a per-competition "sum of ranks" to indicate each user's overall performance in a each competition?

**Comment by euphwes** [comment]
Well, the sum of ranks stats accounts for somebody not having participated in an event: their rank for that event is `(total number of people with ranks in that event) + 1`, so their rank contribution from that event is always worse than somebody who has actually participated.

This way, for example, somebody who has only competed in 3x3 won't have an unfairly low sum of ranks stat compared to a more involved competitor.

Viewed in this light, sum of ranks and "total points this week" are really measuring the same thing, just with a different metric (lower is better for sum of ranks, and higher is better for total points).

Let me think on this a bit! The leaderboard pages are already a little bit slow (lots of data crunching and database queries happening there), and I don't want to exacerbate the problem. There's probably an intelligent way to make the leaderboards faster, and when I do that, I think it would make sense to add this in.

**Comment by topppits** [comment]
>Well, the sum of ranks stats accounts for somebody not having participated in an event: their rank for that event is (total number of people with ranks in that event) + 1, so their rank contribution from that event is always worse than somebody who has actually participated.

Right, I know this, idk wtf I was thinking.

>There's probably an intelligent way to make the leaderboards faster, and when I do that, I think it would make sense to add this in.

Perfect :)
