### ISSUE TITLE
Improve 3x3 scramble preview aesthetics

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#167]
Right now all the cubies are rounded the same amount, but this isn't how real life cubes look. Start with 3x3, and see if I can adjust the polygon corner rounding to match what a real cube looks like. If it turns out to be extensible, maybe apply that to 2x2, 4x4+, and/or other events.

**Comment by euphwes** [comment]
![image](https://user-images.githubusercontent.com/5588930/113787488-5b22df80-96f8-11eb-97a6-661c977bf24a.png)

Came up with that on the left, and asked around. Some people like the current aesthetic (right), some people like the left. Maybe I make it an option?

**Comment by topppits** [comment]
Making it an option sounds perfect. I don't mind it on 3x3, but on 5x5 for example I imagine the left view to be much easier to compare to.

**Comment by euphwes** [comment]
3 years later, finally got around to implementing this for 2x2, 3x3, and 4x4!

![image](https://github.com/euphwes/cubers.io/assets/5588930/ed6fb350-5c6b-449d-befe-209c47b8feec)

![image](https://github.com/euphwes/cubers.io/assets/5588930/a631d321-476b-4099-b726-79601f2f63f8)

![image](https://github.com/euphwes/cubers.io/assets/5588930/7b8f05c0-0fb6-4d15-9276-8276f032662c)
