### ISSUE TITLE
Scrollbar appears on firefox

### ISSUE THREAD

**Issue by xsrvmy** [euphwes/cubers.io#189]
On the solving page, a scrollbar appears on the page in Firefox but not Chrome (I'm guessing this is why it was overlooked).
It is possible to fix the bug by changing the height from `calc(100% - 48px)` to `calc(100vh - 48px)`.

**Comment by euphwes** [comment]
Thanks for the bug report! I'm definitely not a front-end focused guy, so reports (and proposed fixes like these) are great, and I don't often use Firefox to test. Thanks! I'll get this fixed ASAP.

**Comment by euphwes** [comment]
A million years later, I'm finally doing some quality of life updates and rediscovered this ticket. Fixing in an upcoming release!
