### ISSUE TITLE
3x3 feet still listed as WCA event

### ISSUE THREAD

**Issue by TheRealUncleFrank** [euphwes/cubers.io#197]
Main page > Records > WCA Events
3x3 Feet should be moved to Non-wca Events.

I can't tell if Records > Kinch Ranks > WCA Events
or Records > Sum of Ranks > WCA Events
still includes Feet or not.

**Comment by euphwes** [comment]
Good catch! I'll move 3x3 With Feet over to non-WCA. Right now, with feet is still included under WCA Kinch and sum of ranks, so I'll get that fixed too. Thanks for opening this[](url)
