### ISSUE TITLE
Suggestion: Add a scramble for the COLL event

### ISSUE THREAD

**Issue by edladd84** [euphwes/cubers.io#21]
In addition to saying "This week we're doing COLL C3", can we have a scramble to set up the case?

**Comment by euphwes** [comment]
Sounds good! This is one of those small things where I picked up how the old competition posting script used to work, but didn't make any modifications.

I can use the [algs here at algdb.net](http://algdb.net/puzzle/333/coll) as inverse scrambles, and randomly select from the few listed for each case to keep things mixed up.

Thanks for the suggestion - I'll get this knocked out soon.

**Comment by euphwes** [comment]
This is finished! You'll now see COLL setup algs, plus informational links to algdb.net and Speedsolving wiki, for each COLL case as that event comes around. This will start the next time COLL comes around as a bonus event. It'll look like this:

![coll scrambles](https://i.imgur.com/f6LKOyp.png)

This consists of an inverse COLL alg with a random EPLL tacked on to the beginning or end of the inverse alg. This will set up the specified COLL case with a random EPLL state.
