### ISSUE TITLE
Addition of Magic and Master Magic

### ISSUE THREAD

**Issue by TaxMas** [euphwes/cubers.io#213]
I think that even if Magic and Master Magic are no more official events, they can still be speedcubed in cubers.io. They don't need any kind of scramble, so they can be more easily added. I know this can be controversial but also an interestin come back of those puzzles.

**Comment by euphwes** [comment]
I'm not going to do any major cleanup efforts or new features here, I plan to rewrite this app in a more modern way at some point soon.

Thanks for the suggestion! I'll consider Magic and Master Magic in a future version of cubers.io, but will want to also weigh that against whether it'll have enough participation to warrant adding them in.
