### ISSUE TITLE
Better visual distinction between lines in megaminx scrambles.

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#26]
Megaminx scrambles consist of logical "lines" that end in a `U` or `U'`. Separate these scramble lines into separate lines of text, or possibly increase horizontal spacing between lines to make each line easier to visually distinguish.

**Comment by dancing-jules** [comment]
If you don't want to do 7 lines, you could do 5 spaces or something and make sure that all line-breaks are after a U/U'.

Like this: 
![image](https://user-images.githubusercontent.com/33940391/52181735-ae860400-27f5-11e9-9762-605765317f6a.png)

I.e. non-breaking spaces between elements of each line.

**Comment by euphwes** [comment]
Good idea @dancing-jules! That's what I ended up doing -- breaking after every 2nd U/U', with additional non-breaking spaces following the other U/U's. I also changed it to a monospace font (just for megaminx), so things line up nicely.

The result looks [like this on desktop](https://i.imgur.com/FxNr2ff.png), and [like this on mobile](https://i.imgur.com/Cpeolvc.png).
