### ISSUE TITLE
Scaling problems when changing screen size and/or zoom factor

### ISSUE THREAD

**Issue by dancing-jules** [euphwes/cubers.io#28]
When I open cubers.io on my browser (Mozilla Firefox) it looks like this:

![image](https://user-images.githubusercontent.com/33940391/52182184-cad86f80-27fa-11e9-9202-682a7691183e.png)

When I zoom IN (not out) it looks like this:

![image](https://user-images.githubusercontent.com/33940391/52182196-f0657900-27fa-11e9-9495-14cb6e92ee15.png)

And no amount of zooming makes the scramble size go back to normal.

In a narrow window it looks like this:

![image](https://user-images.githubusercontent.com/33940391/52182209-1be86380-27fb-11e9-8715-2b233b32533f.png)

The scramble picture is not clickable unless I zoom OUT (not in) where it looks like this: 

![image](https://user-images.githubusercontent.com/33940391/52182220-4b976b80-27fb-11e9-9659-6812e6a642f2.png)

And no amount of zooming makes the font size of the scramble normal again (though if I zoom out far enough, it looks like a smaller version of the second picture).

**Comment by euphwes** [comment]
I'm surprised by the scramble font, that should be adjusting as the screen size adjusts -- I'll look into it. Thanks for the heads-up on the other items! UI is admittedly not my strongest area, so there's definitely work to be done there. I'll be taking a look at this soon and seeing if I can improve some of these elements.

**Comment by euphwes** [comment]
With latest UI rework, the issues as described here don't really exist anymore. Scramble font size is still occasionally an issue, which I'm tracking in #76. Closing this.
