### ISSUE TITLE
Deleting a solve while inspecting DNFs all solves

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#37]
Open a solve page of an event where you have not done any solves for the current comp. Then do your first solve. Then start inspection of the second one (not the solve time itself, only inspection). When deleting the first solve while inspection is still going and then pressing space (one or two times), weird things happen. The updates of the big middle time of inspection and solve overlap, displaying both in very quick succession, and after a bit of time, all solves (of the current event of the current competition) are DNFd. The console logs "auto DNF" repeated a few times every second.

**Comment by euphwes** [comment]
Ooh this is weird, and very interesting. Thanks for logging the issue and giving me detailed steps to reproduce, I can make this happen every time. I'll go take a look and get this ironed out ASAP, hopefully in the next couple of days.
