### ISSUE TITLE
Cancel the timer via esc key without recording time

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#4]
Currently, a running timer can be stopped by pressing any key on the keyboard. However the timer will record a time no matter which key is used to stop. This is problematic if the timer is started accidentally. Intuitively, I'd like the `esc` button to stop the timer *without recording a time*, so I can restart the timer without having to first delete an accidental solve.

Implement this after #3.

**Comment by topppits** [comment]
This should also work during inspection time.
