### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by sggts04** [euphwes/cubers.io#41]
Can this be a thing?

Also thanks for finally open-sourcing this, can't believe I missed it getting open-sourced. I'm the guy who used your pyTwistyScrambler to build [pyCubeTimer](https://github.com/sggts04/pycubetimer) if you remember

**Comment by euphwes** [comment]
You bet! Adding a dark mode was also mentioned in #13. I've been thinking about it, I just haven't gotten around to it yet. Honestly it's probably straightforward with a clean LESS/CSS starting point, but I'm not really a front-end guy so the styling has grown a bit hairy over the last few months...

I'm definitely open to it though.

Glad you're happy it's open-source now! I announced it a few months back, but it's easy to miss posts on Reddit. I do remember your timer and chatting with you a bit about the scrambling library :-)

**Comment by euphwes** [comment]
I'm not going to do any major cleanup efforts or new features here, I plan to rewrite this app in a more modern way at some point. This is still a great idea, and I'll make sure it happens in a rewrite of the app!
