### ISSUE TITLE
Changing the event while the preselected competition leaderboard event loads leads to no data displayed for a while

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#45]
Steps to reproduce: Load the current competition leaderboard. While the cube animation is displayed, select any not selected event. After a few seconds, it looks like this: https://imgur.com/a/Rb7qCQm . A bit later, the correct data appears.

Details: When loading a competition leaderboard (for example https://www.cubers.io/leaderboards/60/), first the menu and event selection appears, but the results for the selected events are loaded seperately (shifting cube animation displays during that phase). When selecting any event other than the preselected one while that data is still loading, the cube animation is removed after a while, but the data is not displayed (presumably it loads the data for the old event). At that point, it looks like this: https://imgur.com/a/Rb7qCQm. A few seconds later, the data of the new event is displayed.

What I think is happening is that the loader of the first event removes the animation after it is finished, but does not display the data as the data it has loaded is not associated to the current event at the time it has loaded. Switching the event could cause the loader animation to be displayed, but it already is.

**Comment by euphwes** [comment]
I think you're right, I'm not properly accounting for a new event being clicked to load when another one is in progress. I'll get a fix out ASAP. Thanks for the report and the steps to reproduce.
