### ISSUE TITLE
2x2x2 Scrambles are not showing on competition leaderboard

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#46]
When going to here (https://www.cubers.io/leaderboards/60/), selecting the 2x2 event and clicking the button which usually shows the scrambles, an error gets logged to the console and the scrambles don't show. I checked some other events and they seem to work, it is just 2x2x2 (EDIT: and COLL and PLL time attack).

TypeError: cannot use 'in' operator to search for 'length' in '['F R U2 R U F2 ...' jquery.min.js:2:3515
The error seems to happen in line 752, which is in the onclick handler of the scramble button.

**Comment by euphwes** [comment]
Huh that's weird, I'm not sure exactly what's going on there but I'll take a look and get it ironed out soon. Thanks!
