### ISSUE TITLE
Hidden scramble image after finishing an event is not hidden enough

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#47]
If you finish an event by completing all solves, the average is shown at the top and the scramble image is removed. However it is not completely removed, clicking where it was before still counts as a click on the image and causes the image to go full screen. Also resizing the screen (for example by opening the web console which was closed before) shows the image completely.
I think the image should be completely hidden in that situation as there is no solve to do at that point and a scramble image for no solve seems unnecessary to me.

**Comment by euphwes** [comment]
Good call, I'll work a fix such that the image preview area is actually inert or completely hidden once all solves are complete. Thanks!
