### ISSUE TITLE
Are you open to contributions?

### ISSUE THREAD

**Issue by dsoegijono** [euphwes/cubers.io#52]
If so, it would be very helpful to have a guide, something like `Contributing.md` (something like [this](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)). At the very least, how to set up and run the app locally.

**Comment by euphwes** [comment]
Hi! I'm definitely open to contributions -- your idea is a good one, I will definitely get a setup guide written and posted as soon as possible. Thanks!
