### ISSUE TITLE
Time on screen reverts to first solve of session

### ISSUE THREAD

**Issue by dsoegijono** [euphwes/cubers.io#66]
If I've solved 3 out of the 5, seems like the time on screen always reverts to the first solve. Therefore, when I do any action (like delete or +2), it does to the first solve instead of the third/latest solve.

See screenshot:
<img width="1440" alt="Screen Shot 2019-06-10 at 11 36 29" src="https://user-images.githubusercontent.com/867840/59172773-1a95c180-8b74-11e9-9d32-a298e366dad2.png">

**Comment by dsoegijono** [comment]
I just tried deleting solves, and it went from deleting solve 1, 3, 4, then 2.

**Comment by euphwes** [comment]
Hmm, weird. Sorry about that! I think I know what's going on; I'm assuming my database queries are ordering the solves by scramble ID. That would normally happen, but that's not guaranteed since I'm not specifying an explicit "order by". I'll look into it, get the explicit ordering fixed ASAP.

Thanks again!

**Comment by dsoegijono** [comment]
Thanks! I tried deleting all solves, and solving again, and it was still happening. This time around, deleting went from solve 1,4,3,2, so I think it was only stuck on 1, then went correctly.

I was on firefox, not sure if it matters, just in case the browser is doing something strange

**Comment by euphwes** [comment]
Nah, the browser should be irrelevant here; all the logic of which solve is the previous one happens server-side. Totally my issue, not yours or your browser :-) Thanks for quick and thorough bug report! I'll get it ironed out shortly.

**Comment by euphwes** [comment]
Is this still happening for you? I just pushed out a potential fix that I think should do the trick, but it's hard for me to test directly since I'm not experiencing the problem myself.

**Comment by dsoegijono** [comment]
Seems to have been fixed. Thanks for the quick response!
