### ISSUE TITLE
Using spaces in event comment interacts with timer directly after finishing events

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#70]
When typing in a comment after doing an event, using spaces is able to start the timer. Closing the comment input while having the timer started results in crazy big numbers (26004008 minutes) getting displayed as the timer input, these seem to be related to `+new Date()/60000`, looks like the start date does not get set correctly. When stopping the extra solve, this gets displayed:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
This issue does not happen when loading a page of an already finished event, only when finishing the event and then commenting immediately

**Comment by euphwes** [comment]
Oops...

It was a gap in the logic on my side; I had hooks surrounding opening the comment box to disable the timer for the duration the comment box is open, so the spacebar wouldn't trigger it stop and start.

I just (for some reason) was only doing that enabling/disabling of the timer if the event wasn't complete. If it was complete, I left the timer's state along, and so an enabled timer would still intercept the spacebar.

Should be all buttoned up now. Thanks or the report!
