### ISSUE TITLE
Some BLD means don't show

### ISSUE THREAD

**Issue by CMOSSystem** [euphwes/cubers.io#72]
For example here: https://www.cubers.io/leaderboards/72/
In some rows, even if all three attempts are solved (a time put in) or DNF, the mean is not shown. In other ones it is shown, with no obvious pattern.
![grafik](https://user-images.githubusercontent.com/35967119/59507413-4635e600-8eab-11e9-9422-280a77323f73.png)

**Comment by euphwes** [comment]
Oops. The pattern is that the result sets that were finished after I fixed MBLD creating bogus means bug (#69). I was too heavy-handed there and accidentally prevented all best-of-3 events from attempting to calculate means, not all of them. This is just great proof how bad any given developer is at thoroughly testing their software.

I will get a fix out ASAP; thanks for the report!
