### ISSUE TITLE
Add back solve-edit context menu to solves

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#82]
Right now you can only modify the most recent solve. People seem to be missing the ability to edit any previous solve, so add back the context menu that was there before.

**Comment by euphwes** [comment]
Decided not to do this after all, haven't heard anything about it for a while and people seem to be happy with the way you can alter penalties for the previous solve.

**Comment by topppits** [comment]
I think most people just didn't say anything because they knew you wanted to implemented eventually, at least that's the case for me.

If you really don't implement it, could you implement another way to get the scrambles? Pretty often after a 4BLD solve I want to get the scramble to check where I messed up and have to delete the solve(s) to get them.

**Comment by euphwes** [comment]
That's totally fair, I'll re-open this and get it implemented soon 👍 I honestly thought people were mostly just getting used to the new UI, but now that I see it's still a wanted feature, I'll bring it back.

Thanks for keeping me honest!

For what it's worth, you can get the scrambles for an event by going to the leaderboard for its competition, clicking the tab for that event, and then clicking the dice icon at the top-right. That'll give you a pop-up that contains that event's scrambles!

**Comment by topppits** [comment]
Thx!

Uh, I think at one point I knew about the dice but forgot, thx!

**Comment by euphwes** [comment]
Work is underway! Got the hard stuff knocked out tonight, just need to plug the rest of the pieces together. I'll get this pushed out in the next day or so, I bet.

**Comment by euphwes** [comment]
Done! It's live now, check it out and let me know what you think :-)

**Comment by topppits** [comment]
Yes! Perfect! :)

At least on desktop. Mobile looks a bit broken, tested with Chrome and Opera beta.

**Comment by euphwes** [comment]
Aww crap, you're right. I don't personally use mobile very often, so I sometimes forget to check that. I'll get it fixed in the next couple hours.

**Comment by euphwes** [comment]
Fixed in mobile! Sorry for the half-assed job, haha, it was late when I got it all done and forgot to make some minor tweaks to the mobile stuff to accommodate.
