### ISSUE TITLE
Stackmat support

### ISSUE THREAD

**Issue by euphwes** [euphwes/cubers.io#9]
Add support for starting and stopping the timer via Stackmat.

**Comment by topppits** [comment]
For the speedstacks stackmat some timers are able to trigger the inspection time when you tap both sensors shortly (<0.55s). For other stackmat timers this does not seem to work. Please make inspection time triggerable by space bar in stackmat mode.

**Comment by euphwes** [comment]
I'm not going to do any new major features here, I plan to rewrite this app in a more modern way at some point. I'd still like Stackmat support to be possible in the future.
